[package]
name = "Hello, World?"
version = "0.1.0"
edition = "2025"
authors = ["Barto- helloworldgame.xyz"]
description = "An AI-driven town simulation with conscious and unconscious NPCs"

[dependencies]
# Async Runtime
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Graphics and Game Engine
bevy = "0.12"
bevy_sprite = "0.12"
bevy_tilemap = "0.12"

# AI and Machine Learning
petgraph = "0.6"        # For relationship graphs
rand = "0.8"            # For randomization
rand_distr = "0.4"      # For more complex distributions
pathfinding = "4.3"     # For NPC pathfinding
rust-bert = "0.20"      # For NLP tasks
tokenizers = "0.13"     # For text processing

# Data Structures and Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ron = "0.8"             # Rusty Object Notation

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "json", "chrono", "uuid"] }

# Networking
tungstenite = "0.20"    # WebSocket
tokio-tungstenite = "0.20"
axum = "0.7"            # Web framework

# Utilities
uuid = { version = "1.4", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"
anyhow = "1.0"

# Parallel Processing
rayon = "1.7"
crossbeam = "0.8"
parking_lot = "0.12"

# Configuration
config = "0.13"
dotenv = "0.15"

[dev-dependencies]
criterion = "0.5"       # For benchmarking
mockall = "0.11"        # For mocking in tests
rstest = "0.18"         # For parameterized testing
test-case = "3.1"
tokio-test = "0.4"

[profile.dev]
opt-level = 1          # Basic optimizations for dev
debug = true

[profile.release]
opt-level = 3          # Maximum optimizations
lto = true             # Link-time optimization
codegen-units = 1      # Maximize optimizations
debug = false

[workspace]
members = [
    "crates/ai_core",
    "crates/engine",
    "crates/networking",
]

[[bench]]
name = "ai_benchmarks"
harness = false
